# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _SwigModule
else:
    import _SwigModule

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class MyClass1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass1_swiginit(self, _SwigModule.new_MyClass1())
    __swig_destroy__ = _SwigModule.delete_MyClass1

# Register MyClass1 in _SwigModule:
_SwigModule.MyClass1_swigregister(MyClass1)

class MyClass2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass2_swiginit(self, _SwigModule.new_MyClass2())
    __swig_destroy__ = _SwigModule.delete_MyClass2

# Register MyClass2 in _SwigModule:
_SwigModule.MyClass2_swigregister(MyClass2)

class MyClass3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass3_swiginit(self, _SwigModule.new_MyClass3())
    __swig_destroy__ = _SwigModule.delete_MyClass3

# Register MyClass3 in _SwigModule:
_SwigModule.MyClass3_swigregister(MyClass3)

class MyClass4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass4_swiginit(self, _SwigModule.new_MyClass4())
    __swig_destroy__ = _SwigModule.delete_MyClass4

# Register MyClass4 in _SwigModule:
_SwigModule.MyClass4_swigregister(MyClass4)

class MyClass5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass5_swiginit(self, _SwigModule.new_MyClass5())
    __swig_destroy__ = _SwigModule.delete_MyClass5

# Register MyClass5 in _SwigModule:
_SwigModule.MyClass5_swigregister(MyClass5)

class MyClass6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass6_swiginit(self, _SwigModule.new_MyClass6())
    __swig_destroy__ = _SwigModule.delete_MyClass6

# Register MyClass6 in _SwigModule:
_SwigModule.MyClass6_swigregister(MyClass6)

class MyClass7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass7_swiginit(self, _SwigModule.new_MyClass7())
    __swig_destroy__ = _SwigModule.delete_MyClass7

# Register MyClass7 in _SwigModule:
_SwigModule.MyClass7_swigregister(MyClass7)

class MyClass8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass8_swiginit(self, _SwigModule.new_MyClass8())
    __swig_destroy__ = _SwigModule.delete_MyClass8

# Register MyClass8 in _SwigModule:
_SwigModule.MyClass8_swigregister(MyClass8)

class MyClass9(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass9_swiginit(self, _SwigModule.new_MyClass9())
    __swig_destroy__ = _SwigModule.delete_MyClass9

# Register MyClass9 in _SwigModule:
_SwigModule.MyClass9_swigregister(MyClass9)

class MyClass0(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass0_swiginit(self, _SwigModule.new_MyClass0())
    __swig_destroy__ = _SwigModule.delete_MyClass0

# Register MyClass0 in _SwigModule:
_SwigModule.MyClass0_swigregister(MyClass0)

class MyClass11(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass11_swiginit(self, _SwigModule.new_MyClass11())
    __swig_destroy__ = _SwigModule.delete_MyClass11

# Register MyClass11 in _SwigModule:
_SwigModule.MyClass11_swigregister(MyClass11)

class MyClass12(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass12_swiginit(self, _SwigModule.new_MyClass12())
    __swig_destroy__ = _SwigModule.delete_MyClass12

# Register MyClass12 in _SwigModule:
_SwigModule.MyClass12_swigregister(MyClass12)

class MyClass13(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass13_swiginit(self, _SwigModule.new_MyClass13())
    __swig_destroy__ = _SwigModule.delete_MyClass13

# Register MyClass13 in _SwigModule:
_SwigModule.MyClass13_swigregister(MyClass13)

class MyClass14(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass14_swiginit(self, _SwigModule.new_MyClass14())
    __swig_destroy__ = _SwigModule.delete_MyClass14

# Register MyClass14 in _SwigModule:
_SwigModule.MyClass14_swigregister(MyClass14)

class MyClass15(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass15_swiginit(self, _SwigModule.new_MyClass15())
    __swig_destroy__ = _SwigModule.delete_MyClass15

# Register MyClass15 in _SwigModule:
_SwigModule.MyClass15_swigregister(MyClass15)

class MyClass16(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass16_swiginit(self, _SwigModule.new_MyClass16())
    __swig_destroy__ = _SwigModule.delete_MyClass16

# Register MyClass16 in _SwigModule:
_SwigModule.MyClass16_swigregister(MyClass16)

class MyClass17(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass17_swiginit(self, _SwigModule.new_MyClass17())
    __swig_destroy__ = _SwigModule.delete_MyClass17

# Register MyClass17 in _SwigModule:
_SwigModule.MyClass17_swigregister(MyClass17)

class MyClass18(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass18_swiginit(self, _SwigModule.new_MyClass18())
    __swig_destroy__ = _SwigModule.delete_MyClass18

# Register MyClass18 in _SwigModule:
_SwigModule.MyClass18_swigregister(MyClass18)

class MyClass19(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass19_swiginit(self, _SwigModule.new_MyClass19())
    __swig_destroy__ = _SwigModule.delete_MyClass19

# Register MyClass19 in _SwigModule:
_SwigModule.MyClass19_swigregister(MyClass19)

class MyClass20(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass20_swiginit(self, _SwigModule.new_MyClass20())
    __swig_destroy__ = _SwigModule.delete_MyClass20

# Register MyClass20 in _SwigModule:
_SwigModule.MyClass20_swigregister(MyClass20)

class MyClass21(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass21_swiginit(self, _SwigModule.new_MyClass21())
    __swig_destroy__ = _SwigModule.delete_MyClass21

# Register MyClass21 in _SwigModule:
_SwigModule.MyClass21_swigregister(MyClass21)

class MyClass22(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass22_swiginit(self, _SwigModule.new_MyClass22())
    __swig_destroy__ = _SwigModule.delete_MyClass22

# Register MyClass22 in _SwigModule:
_SwigModule.MyClass22_swigregister(MyClass22)

class MyClass23(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass23_swiginit(self, _SwigModule.new_MyClass23())
    __swig_destroy__ = _SwigModule.delete_MyClass23

# Register MyClass23 in _SwigModule:
_SwigModule.MyClass23_swigregister(MyClass23)

class MyClass24(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass24_swiginit(self, _SwigModule.new_MyClass24())
    __swig_destroy__ = _SwigModule.delete_MyClass24

# Register MyClass24 in _SwigModule:
_SwigModule.MyClass24_swigregister(MyClass24)

class MyClass25(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass25_swiginit(self, _SwigModule.new_MyClass25())
    __swig_destroy__ = _SwigModule.delete_MyClass25

# Register MyClass25 in _SwigModule:
_SwigModule.MyClass25_swigregister(MyClass25)

class MyClass26(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass26_swiginit(self, _SwigModule.new_MyClass26())
    __swig_destroy__ = _SwigModule.delete_MyClass26

# Register MyClass26 in _SwigModule:
_SwigModule.MyClass26_swigregister(MyClass26)

class MyClass27(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass27_swiginit(self, _SwigModule.new_MyClass27())
    __swig_destroy__ = _SwigModule.delete_MyClass27

# Register MyClass27 in _SwigModule:
_SwigModule.MyClass27_swigregister(MyClass27)

class MyClass28(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass28_swiginit(self, _SwigModule.new_MyClass28())
    __swig_destroy__ = _SwigModule.delete_MyClass28

# Register MyClass28 in _SwigModule:
_SwigModule.MyClass28_swigregister(MyClass28)

class MyClass29(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass29_swiginit(self, _SwigModule.new_MyClass29())
    __swig_destroy__ = _SwigModule.delete_MyClass29

# Register MyClass29 in _SwigModule:
_SwigModule.MyClass29_swigregister(MyClass29)

class MyClass30(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass30_swiginit(self, _SwigModule.new_MyClass30())
    __swig_destroy__ = _SwigModule.delete_MyClass30

# Register MyClass30 in _SwigModule:
_SwigModule.MyClass30_swigregister(MyClass30)

class MyClass31(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass31_swiginit(self, _SwigModule.new_MyClass31())
    __swig_destroy__ = _SwigModule.delete_MyClass31

# Register MyClass31 in _SwigModule:
_SwigModule.MyClass31_swigregister(MyClass31)

class MyClass32(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass32_swiginit(self, _SwigModule.new_MyClass32())
    __swig_destroy__ = _SwigModule.delete_MyClass32

# Register MyClass32 in _SwigModule:
_SwigModule.MyClass32_swigregister(MyClass32)

class MyClass33(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass33_swiginit(self, _SwigModule.new_MyClass33())
    __swig_destroy__ = _SwigModule.delete_MyClass33

# Register MyClass33 in _SwigModule:
_SwigModule.MyClass33_swigregister(MyClass33)

class MyClass34(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass34_swiginit(self, _SwigModule.new_MyClass34())
    __swig_destroy__ = _SwigModule.delete_MyClass34

# Register MyClass34 in _SwigModule:
_SwigModule.MyClass34_swigregister(MyClass34)

class MyClass35(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass35_swiginit(self, _SwigModule.new_MyClass35())
    __swig_destroy__ = _SwigModule.delete_MyClass35

# Register MyClass35 in _SwigModule:
_SwigModule.MyClass35_swigregister(MyClass35)

class MyClass36(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass36_swiginit(self, _SwigModule.new_MyClass36())
    __swig_destroy__ = _SwigModule.delete_MyClass36

# Register MyClass36 in _SwigModule:
_SwigModule.MyClass36_swigregister(MyClass36)

class MyClass37(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass37_swiginit(self, _SwigModule.new_MyClass37())
    __swig_destroy__ = _SwigModule.delete_MyClass37

# Register MyClass37 in _SwigModule:
_SwigModule.MyClass37_swigregister(MyClass37)

class MyClass38(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass38_swiginit(self, _SwigModule.new_MyClass38())
    __swig_destroy__ = _SwigModule.delete_MyClass38

# Register MyClass38 in _SwigModule:
_SwigModule.MyClass38_swigregister(MyClass38)

class MyClass39(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass39_swiginit(self, _SwigModule.new_MyClass39())
    __swig_destroy__ = _SwigModule.delete_MyClass39

# Register MyClass39 in _SwigModule:
_SwigModule.MyClass39_swigregister(MyClass39)

class MyClass40(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass40_swiginit(self, _SwigModule.new_MyClass40())
    __swig_destroy__ = _SwigModule.delete_MyClass40

# Register MyClass40 in _SwigModule:
_SwigModule.MyClass40_swigregister(MyClass40)

class MyClass41(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass41_swiginit(self, _SwigModule.new_MyClass41())
    __swig_destroy__ = _SwigModule.delete_MyClass41

# Register MyClass41 in _SwigModule:
_SwigModule.MyClass41_swigregister(MyClass41)

class MyClass42(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass42_swiginit(self, _SwigModule.new_MyClass42())
    __swig_destroy__ = _SwigModule.delete_MyClass42

# Register MyClass42 in _SwigModule:
_SwigModule.MyClass42_swigregister(MyClass42)

class MyClass43(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass43_swiginit(self, _SwigModule.new_MyClass43())
    __swig_destroy__ = _SwigModule.delete_MyClass43

# Register MyClass43 in _SwigModule:
_SwigModule.MyClass43_swigregister(MyClass43)

class MyClass44(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass44_swiginit(self, _SwigModule.new_MyClass44())
    __swig_destroy__ = _SwigModule.delete_MyClass44

# Register MyClass44 in _SwigModule:
_SwigModule.MyClass44_swigregister(MyClass44)

class MyClass45(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass45_swiginit(self, _SwigModule.new_MyClass45())
    __swig_destroy__ = _SwigModule.delete_MyClass45

# Register MyClass45 in _SwigModule:
_SwigModule.MyClass45_swigregister(MyClass45)

class MyClass46(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass46_swiginit(self, _SwigModule.new_MyClass46())
    __swig_destroy__ = _SwigModule.delete_MyClass46

# Register MyClass46 in _SwigModule:
_SwigModule.MyClass46_swigregister(MyClass46)

class MyClass47(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass47_swiginit(self, _SwigModule.new_MyClass47())
    __swig_destroy__ = _SwigModule.delete_MyClass47

# Register MyClass47 in _SwigModule:
_SwigModule.MyClass47_swigregister(MyClass47)

class MyClass48(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass48_swiginit(self, _SwigModule.new_MyClass48())
    __swig_destroy__ = _SwigModule.delete_MyClass48

# Register MyClass48 in _SwigModule:
_SwigModule.MyClass48_swigregister(MyClass48)

class MyClass49(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass49_swiginit(self, _SwigModule.new_MyClass49())
    __swig_destroy__ = _SwigModule.delete_MyClass49

# Register MyClass49 in _SwigModule:
_SwigModule.MyClass49_swigregister(MyClass49)

class MyClass50(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass50_swiginit(self, _SwigModule.new_MyClass50())
    __swig_destroy__ = _SwigModule.delete_MyClass50

# Register MyClass50 in _SwigModule:
_SwigModule.MyClass50_swigregister(MyClass50)

class MyClass51(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass51_swiginit(self, _SwigModule.new_MyClass51())
    __swig_destroy__ = _SwigModule.delete_MyClass51

# Register MyClass51 in _SwigModule:
_SwigModule.MyClass51_swigregister(MyClass51)

class MyClass52(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass52_swiginit(self, _SwigModule.new_MyClass52())
    __swig_destroy__ = _SwigModule.delete_MyClass52

# Register MyClass52 in _SwigModule:
_SwigModule.MyClass52_swigregister(MyClass52)

class MyClass53(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass53_swiginit(self, _SwigModule.new_MyClass53())
    __swig_destroy__ = _SwigModule.delete_MyClass53

# Register MyClass53 in _SwigModule:
_SwigModule.MyClass53_swigregister(MyClass53)

class MyClass54(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass54_swiginit(self, _SwigModule.new_MyClass54())
    __swig_destroy__ = _SwigModule.delete_MyClass54

# Register MyClass54 in _SwigModule:
_SwigModule.MyClass54_swigregister(MyClass54)

class MyClass55(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass55_swiginit(self, _SwigModule.new_MyClass55())
    __swig_destroy__ = _SwigModule.delete_MyClass55

# Register MyClass55 in _SwigModule:
_SwigModule.MyClass55_swigregister(MyClass55)

class MyClass56(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass56_swiginit(self, _SwigModule.new_MyClass56())
    __swig_destroy__ = _SwigModule.delete_MyClass56

# Register MyClass56 in _SwigModule:
_SwigModule.MyClass56_swigregister(MyClass56)

class MyClass57(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass57_swiginit(self, _SwigModule.new_MyClass57())
    __swig_destroy__ = _SwigModule.delete_MyClass57

# Register MyClass57 in _SwigModule:
_SwigModule.MyClass57_swigregister(MyClass57)

class MyClass58(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass58_swiginit(self, _SwigModule.new_MyClass58())
    __swig_destroy__ = _SwigModule.delete_MyClass58

# Register MyClass58 in _SwigModule:
_SwigModule.MyClass58_swigregister(MyClass58)

class MyClass59(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass59_swiginit(self, _SwigModule.new_MyClass59())
    __swig_destroy__ = _SwigModule.delete_MyClass59

# Register MyClass59 in _SwigModule:
_SwigModule.MyClass59_swigregister(MyClass59)

class MyClass60(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass60_swiginit(self, _SwigModule.new_MyClass60())
    __swig_destroy__ = _SwigModule.delete_MyClass60

# Register MyClass60 in _SwigModule:
_SwigModule.MyClass60_swigregister(MyClass60)

class MyClass61(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass61_swiginit(self, _SwigModule.new_MyClass61())
    __swig_destroy__ = _SwigModule.delete_MyClass61

# Register MyClass61 in _SwigModule:
_SwigModule.MyClass61_swigregister(MyClass61)

class MyClass62(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass62_swiginit(self, _SwigModule.new_MyClass62())
    __swig_destroy__ = _SwigModule.delete_MyClass62

# Register MyClass62 in _SwigModule:
_SwigModule.MyClass62_swigregister(MyClass62)

class MyClass63(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass63_swiginit(self, _SwigModule.new_MyClass63())
    __swig_destroy__ = _SwigModule.delete_MyClass63

# Register MyClass63 in _SwigModule:
_SwigModule.MyClass63_swigregister(MyClass63)

class MyClass64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass64_swiginit(self, _SwigModule.new_MyClass64())
    __swig_destroy__ = _SwigModule.delete_MyClass64

# Register MyClass64 in _SwigModule:
_SwigModule.MyClass64_swigregister(MyClass64)

class MyClass65(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass65_swiginit(self, _SwigModule.new_MyClass65())
    __swig_destroy__ = _SwigModule.delete_MyClass65

# Register MyClass65 in _SwigModule:
_SwigModule.MyClass65_swigregister(MyClass65)

class MyClass66(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass66_swiginit(self, _SwigModule.new_MyClass66())
    __swig_destroy__ = _SwigModule.delete_MyClass66

# Register MyClass66 in _SwigModule:
_SwigModule.MyClass66_swigregister(MyClass66)

class MyClass67(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass67_swiginit(self, _SwigModule.new_MyClass67())
    __swig_destroy__ = _SwigModule.delete_MyClass67

# Register MyClass67 in _SwigModule:
_SwigModule.MyClass67_swigregister(MyClass67)

class MyClass68(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass68_swiginit(self, _SwigModule.new_MyClass68())
    __swig_destroy__ = _SwigModule.delete_MyClass68

# Register MyClass68 in _SwigModule:
_SwigModule.MyClass68_swigregister(MyClass68)

class MyClass69(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass69_swiginit(self, _SwigModule.new_MyClass69())
    __swig_destroy__ = _SwigModule.delete_MyClass69

# Register MyClass69 in _SwigModule:
_SwigModule.MyClass69_swigregister(MyClass69)

class MyClass70(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass70_swiginit(self, _SwigModule.new_MyClass70())
    __swig_destroy__ = _SwigModule.delete_MyClass70

# Register MyClass70 in _SwigModule:
_SwigModule.MyClass70_swigregister(MyClass70)

class MyClass71(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass71_swiginit(self, _SwigModule.new_MyClass71())
    __swig_destroy__ = _SwigModule.delete_MyClass71

# Register MyClass71 in _SwigModule:
_SwigModule.MyClass71_swigregister(MyClass71)

class MyClass72(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass72_swiginit(self, _SwigModule.new_MyClass72())
    __swig_destroy__ = _SwigModule.delete_MyClass72

# Register MyClass72 in _SwigModule:
_SwigModule.MyClass72_swigregister(MyClass72)

class MyClass73(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass73_swiginit(self, _SwigModule.new_MyClass73())
    __swig_destroy__ = _SwigModule.delete_MyClass73

# Register MyClass73 in _SwigModule:
_SwigModule.MyClass73_swigregister(MyClass73)

class MyClass74(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass74_swiginit(self, _SwigModule.new_MyClass74())
    __swig_destroy__ = _SwigModule.delete_MyClass74

# Register MyClass74 in _SwigModule:
_SwigModule.MyClass74_swigregister(MyClass74)

class MyClass75(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass75_swiginit(self, _SwigModule.new_MyClass75())
    __swig_destroy__ = _SwigModule.delete_MyClass75

# Register MyClass75 in _SwigModule:
_SwigModule.MyClass75_swigregister(MyClass75)

class MyClass76(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass76_swiginit(self, _SwigModule.new_MyClass76())
    __swig_destroy__ = _SwigModule.delete_MyClass76

# Register MyClass76 in _SwigModule:
_SwigModule.MyClass76_swigregister(MyClass76)

class MyClass77(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass77_swiginit(self, _SwigModule.new_MyClass77())
    __swig_destroy__ = _SwigModule.delete_MyClass77

# Register MyClass77 in _SwigModule:
_SwigModule.MyClass77_swigregister(MyClass77)

class MyClass78(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass78_swiginit(self, _SwigModule.new_MyClass78())
    __swig_destroy__ = _SwigModule.delete_MyClass78

# Register MyClass78 in _SwigModule:
_SwigModule.MyClass78_swigregister(MyClass78)

class MyClass79(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass79_swiginit(self, _SwigModule.new_MyClass79())
    __swig_destroy__ = _SwigModule.delete_MyClass79

# Register MyClass79 in _SwigModule:
_SwigModule.MyClass79_swigregister(MyClass79)

class MyClass80(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass80_swiginit(self, _SwigModule.new_MyClass80())
    __swig_destroy__ = _SwigModule.delete_MyClass80

# Register MyClass80 in _SwigModule:
_SwigModule.MyClass80_swigregister(MyClass80)

class MyClass81(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass81_swiginit(self, _SwigModule.new_MyClass81())
    __swig_destroy__ = _SwigModule.delete_MyClass81

# Register MyClass81 in _SwigModule:
_SwigModule.MyClass81_swigregister(MyClass81)

class MyClass82(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass82_swiginit(self, _SwigModule.new_MyClass82())
    __swig_destroy__ = _SwigModule.delete_MyClass82

# Register MyClass82 in _SwigModule:
_SwigModule.MyClass82_swigregister(MyClass82)

class MyClass83(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass83_swiginit(self, _SwigModule.new_MyClass83())
    __swig_destroy__ = _SwigModule.delete_MyClass83

# Register MyClass83 in _SwigModule:
_SwigModule.MyClass83_swigregister(MyClass83)

class MyClass84(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass84_swiginit(self, _SwigModule.new_MyClass84())
    __swig_destroy__ = _SwigModule.delete_MyClass84

# Register MyClass84 in _SwigModule:
_SwigModule.MyClass84_swigregister(MyClass84)

class MyClass85(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass85_swiginit(self, _SwigModule.new_MyClass85())
    __swig_destroy__ = _SwigModule.delete_MyClass85

# Register MyClass85 in _SwigModule:
_SwigModule.MyClass85_swigregister(MyClass85)

class MyClass86(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass86_swiginit(self, _SwigModule.new_MyClass86())
    __swig_destroy__ = _SwigModule.delete_MyClass86

# Register MyClass86 in _SwigModule:
_SwigModule.MyClass86_swigregister(MyClass86)

class MyClass87(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass87_swiginit(self, _SwigModule.new_MyClass87())
    __swig_destroy__ = _SwigModule.delete_MyClass87

# Register MyClass87 in _SwigModule:
_SwigModule.MyClass87_swigregister(MyClass87)

class MyClass88(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass88_swiginit(self, _SwigModule.new_MyClass88())
    __swig_destroy__ = _SwigModule.delete_MyClass88

# Register MyClass88 in _SwigModule:
_SwigModule.MyClass88_swigregister(MyClass88)

class MyClass89(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass89_swiginit(self, _SwigModule.new_MyClass89())
    __swig_destroy__ = _SwigModule.delete_MyClass89

# Register MyClass89 in _SwigModule:
_SwigModule.MyClass89_swigregister(MyClass89)

class MyClass90(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass90_swiginit(self, _SwigModule.new_MyClass90())
    __swig_destroy__ = _SwigModule.delete_MyClass90

# Register MyClass90 in _SwigModule:
_SwigModule.MyClass90_swigregister(MyClass90)

class MyClass91(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass91_swiginit(self, _SwigModule.new_MyClass91())
    __swig_destroy__ = _SwigModule.delete_MyClass91

# Register MyClass91 in _SwigModule:
_SwigModule.MyClass91_swigregister(MyClass91)

class MyClass92(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass92_swiginit(self, _SwigModule.new_MyClass92())
    __swig_destroy__ = _SwigModule.delete_MyClass92

# Register MyClass92 in _SwigModule:
_SwigModule.MyClass92_swigregister(MyClass92)

class MyClass93(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass93_swiginit(self, _SwigModule.new_MyClass93())
    __swig_destroy__ = _SwigModule.delete_MyClass93

# Register MyClass93 in _SwigModule:
_SwigModule.MyClass93_swigregister(MyClass93)

class MyClass94(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass94_swiginit(self, _SwigModule.new_MyClass94())
    __swig_destroy__ = _SwigModule.delete_MyClass94

# Register MyClass94 in _SwigModule:
_SwigModule.MyClass94_swigregister(MyClass94)

class MyClass95(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass95_swiginit(self, _SwigModule.new_MyClass95())
    __swig_destroy__ = _SwigModule.delete_MyClass95

# Register MyClass95 in _SwigModule:
_SwigModule.MyClass95_swigregister(MyClass95)

class MyClass96(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass96_swiginit(self, _SwigModule.new_MyClass96())
    __swig_destroy__ = _SwigModule.delete_MyClass96

# Register MyClass96 in _SwigModule:
_SwigModule.MyClass96_swigregister(MyClass96)

class MyClass97(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass97_swiginit(self, _SwigModule.new_MyClass97())
    __swig_destroy__ = _SwigModule.delete_MyClass97

# Register MyClass97 in _SwigModule:
_SwigModule.MyClass97_swigregister(MyClass97)

class MyClass98(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass98_swiginit(self, _SwigModule.new_MyClass98())
    __swig_destroy__ = _SwigModule.delete_MyClass98

# Register MyClass98 in _SwigModule:
_SwigModule.MyClass98_swigregister(MyClass98)

class MyClass99(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass99_swiginit(self, _SwigModule.new_MyClass99())
    __swig_destroy__ = _SwigModule.delete_MyClass99

# Register MyClass99 in _SwigModule:
_SwigModule.MyClass99_swigregister(MyClass99)

class MyClass100(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass100_swiginit(self, _SwigModule.new_MyClass100())
    __swig_destroy__ = _SwigModule.delete_MyClass100

# Register MyClass100 in _SwigModule:
_SwigModule.MyClass100_swigregister(MyClass100)

class MyClass101(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass101_swiginit(self, _SwigModule.new_MyClass101())
    __swig_destroy__ = _SwigModule.delete_MyClass101

# Register MyClass101 in _SwigModule:
_SwigModule.MyClass101_swigregister(MyClass101)

class MyClass102(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass102_swiginit(self, _SwigModule.new_MyClass102())
    __swig_destroy__ = _SwigModule.delete_MyClass102

# Register MyClass102 in _SwigModule:
_SwigModule.MyClass102_swigregister(MyClass102)

class MyClass103(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass103_swiginit(self, _SwigModule.new_MyClass103())
    __swig_destroy__ = _SwigModule.delete_MyClass103

# Register MyClass103 in _SwigModule:
_SwigModule.MyClass103_swigregister(MyClass103)

class MyClass104(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass104_swiginit(self, _SwigModule.new_MyClass104())
    __swig_destroy__ = _SwigModule.delete_MyClass104

# Register MyClass104 in _SwigModule:
_SwigModule.MyClass104_swigregister(MyClass104)

class MyClass105(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass105_swiginit(self, _SwigModule.new_MyClass105())
    __swig_destroy__ = _SwigModule.delete_MyClass105

# Register MyClass105 in _SwigModule:
_SwigModule.MyClass105_swigregister(MyClass105)

class MyClass106(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass106_swiginit(self, _SwigModule.new_MyClass106())
    __swig_destroy__ = _SwigModule.delete_MyClass106

# Register MyClass106 in _SwigModule:
_SwigModule.MyClass106_swigregister(MyClass106)

class MyClass107(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass107_swiginit(self, _SwigModule.new_MyClass107())
    __swig_destroy__ = _SwigModule.delete_MyClass107

# Register MyClass107 in _SwigModule:
_SwigModule.MyClass107_swigregister(MyClass107)

class MyClass108(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass108_swiginit(self, _SwigModule.new_MyClass108())
    __swig_destroy__ = _SwigModule.delete_MyClass108

# Register MyClass108 in _SwigModule:
_SwigModule.MyClass108_swigregister(MyClass108)

class MyClass109(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass109_swiginit(self, _SwigModule.new_MyClass109())
    __swig_destroy__ = _SwigModule.delete_MyClass109

# Register MyClass109 in _SwigModule:
_SwigModule.MyClass109_swigregister(MyClass109)

class MyClass110(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass110_swiginit(self, _SwigModule.new_MyClass110())
    __swig_destroy__ = _SwigModule.delete_MyClass110

# Register MyClass110 in _SwigModule:
_SwigModule.MyClass110_swigregister(MyClass110)

class MyClass111(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass111_swiginit(self, _SwigModule.new_MyClass111())
    __swig_destroy__ = _SwigModule.delete_MyClass111

# Register MyClass111 in _SwigModule:
_SwigModule.MyClass111_swigregister(MyClass111)

class MyClass112(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass112_swiginit(self, _SwigModule.new_MyClass112())
    __swig_destroy__ = _SwigModule.delete_MyClass112

# Register MyClass112 in _SwigModule:
_SwigModule.MyClass112_swigregister(MyClass112)

class MyClass113(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass113_swiginit(self, _SwigModule.new_MyClass113())
    __swig_destroy__ = _SwigModule.delete_MyClass113

# Register MyClass113 in _SwigModule:
_SwigModule.MyClass113_swigregister(MyClass113)

class MyClass114(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass114_swiginit(self, _SwigModule.new_MyClass114())
    __swig_destroy__ = _SwigModule.delete_MyClass114

# Register MyClass114 in _SwigModule:
_SwigModule.MyClass114_swigregister(MyClass114)

class MyClass115(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass115_swiginit(self, _SwigModule.new_MyClass115())
    __swig_destroy__ = _SwigModule.delete_MyClass115

# Register MyClass115 in _SwigModule:
_SwigModule.MyClass115_swigregister(MyClass115)

class MyClass116(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass116_swiginit(self, _SwigModule.new_MyClass116())
    __swig_destroy__ = _SwigModule.delete_MyClass116

# Register MyClass116 in _SwigModule:
_SwigModule.MyClass116_swigregister(MyClass116)

class MyClass117(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass117_swiginit(self, _SwigModule.new_MyClass117())
    __swig_destroy__ = _SwigModule.delete_MyClass117

# Register MyClass117 in _SwigModule:
_SwigModule.MyClass117_swigregister(MyClass117)

class MyClass118(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass118_swiginit(self, _SwigModule.new_MyClass118())
    __swig_destroy__ = _SwigModule.delete_MyClass118

# Register MyClass118 in _SwigModule:
_SwigModule.MyClass118_swigregister(MyClass118)

class MyClass119(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass119_swiginit(self, _SwigModule.new_MyClass119())
    __swig_destroy__ = _SwigModule.delete_MyClass119

# Register MyClass119 in _SwigModule:
_SwigModule.MyClass119_swigregister(MyClass119)

class MyClass120(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass120_swiginit(self, _SwigModule.new_MyClass120())
    __swig_destroy__ = _SwigModule.delete_MyClass120

# Register MyClass120 in _SwigModule:
_SwigModule.MyClass120_swigregister(MyClass120)

class MyClass121(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass121_swiginit(self, _SwigModule.new_MyClass121())
    __swig_destroy__ = _SwigModule.delete_MyClass121

# Register MyClass121 in _SwigModule:
_SwigModule.MyClass121_swigregister(MyClass121)

class MyClass122(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass122_swiginit(self, _SwigModule.new_MyClass122())
    __swig_destroy__ = _SwigModule.delete_MyClass122

# Register MyClass122 in _SwigModule:
_SwigModule.MyClass122_swigregister(MyClass122)

class MyClass123(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass123_swiginit(self, _SwigModule.new_MyClass123())
    __swig_destroy__ = _SwigModule.delete_MyClass123

# Register MyClass123 in _SwigModule:
_SwigModule.MyClass123_swigregister(MyClass123)

class MyClass124(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass124_swiginit(self, _SwigModule.new_MyClass124())
    __swig_destroy__ = _SwigModule.delete_MyClass124

# Register MyClass124 in _SwigModule:
_SwigModule.MyClass124_swigregister(MyClass124)

class MyClass125(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass125_swiginit(self, _SwigModule.new_MyClass125())
    __swig_destroy__ = _SwigModule.delete_MyClass125

# Register MyClass125 in _SwigModule:
_SwigModule.MyClass125_swigregister(MyClass125)

class MyClass126(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass126_swiginit(self, _SwigModule.new_MyClass126())
    __swig_destroy__ = _SwigModule.delete_MyClass126

# Register MyClass126 in _SwigModule:
_SwigModule.MyClass126_swigregister(MyClass126)

class MyClass127(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass127_swiginit(self, _SwigModule.new_MyClass127())
    __swig_destroy__ = _SwigModule.delete_MyClass127

# Register MyClass127 in _SwigModule:
_SwigModule.MyClass127_swigregister(MyClass127)

class MyClass128(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass128_swiginit(self, _SwigModule.new_MyClass128())
    __swig_destroy__ = _SwigModule.delete_MyClass128

# Register MyClass128 in _SwigModule:
_SwigModule.MyClass128_swigregister(MyClass128)

class MyClass129(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass129_swiginit(self, _SwigModule.new_MyClass129())
    __swig_destroy__ = _SwigModule.delete_MyClass129

# Register MyClass129 in _SwigModule:
_SwigModule.MyClass129_swigregister(MyClass129)

class MyClass130(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass130_swiginit(self, _SwigModule.new_MyClass130())
    __swig_destroy__ = _SwigModule.delete_MyClass130

# Register MyClass130 in _SwigModule:
_SwigModule.MyClass130_swigregister(MyClass130)

class MyClass131(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass131_swiginit(self, _SwigModule.new_MyClass131())
    __swig_destroy__ = _SwigModule.delete_MyClass131

# Register MyClass131 in _SwigModule:
_SwigModule.MyClass131_swigregister(MyClass131)

class MyClass132(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass132_swiginit(self, _SwigModule.new_MyClass132())
    __swig_destroy__ = _SwigModule.delete_MyClass132

# Register MyClass132 in _SwigModule:
_SwigModule.MyClass132_swigregister(MyClass132)

class MyClass133(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass133_swiginit(self, _SwigModule.new_MyClass133())
    __swig_destroy__ = _SwigModule.delete_MyClass133

# Register MyClass133 in _SwigModule:
_SwigModule.MyClass133_swigregister(MyClass133)

class MyClass134(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass134_swiginit(self, _SwigModule.new_MyClass134())
    __swig_destroy__ = _SwigModule.delete_MyClass134

# Register MyClass134 in _SwigModule:
_SwigModule.MyClass134_swigregister(MyClass134)

class MyClass135(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass135_swiginit(self, _SwigModule.new_MyClass135())
    __swig_destroy__ = _SwigModule.delete_MyClass135

# Register MyClass135 in _SwigModule:
_SwigModule.MyClass135_swigregister(MyClass135)

class MyClass136(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass136_swiginit(self, _SwigModule.new_MyClass136())
    __swig_destroy__ = _SwigModule.delete_MyClass136

# Register MyClass136 in _SwigModule:
_SwigModule.MyClass136_swigregister(MyClass136)

class MyClass137(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass137_swiginit(self, _SwigModule.new_MyClass137())
    __swig_destroy__ = _SwigModule.delete_MyClass137

# Register MyClass137 in _SwigModule:
_SwigModule.MyClass137_swigregister(MyClass137)

class MyClass138(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass138_swiginit(self, _SwigModule.new_MyClass138())
    __swig_destroy__ = _SwigModule.delete_MyClass138

# Register MyClass138 in _SwigModule:
_SwigModule.MyClass138_swigregister(MyClass138)

class MyClass139(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass139_swiginit(self, _SwigModule.new_MyClass139())
    __swig_destroy__ = _SwigModule.delete_MyClass139

# Register MyClass139 in _SwigModule:
_SwigModule.MyClass139_swigregister(MyClass139)

class MyClass140(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass140_swiginit(self, _SwigModule.new_MyClass140())
    __swig_destroy__ = _SwigModule.delete_MyClass140

# Register MyClass140 in _SwigModule:
_SwigModule.MyClass140_swigregister(MyClass140)

class MyClass141(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass141_swiginit(self, _SwigModule.new_MyClass141())
    __swig_destroy__ = _SwigModule.delete_MyClass141

# Register MyClass141 in _SwigModule:
_SwigModule.MyClass141_swigregister(MyClass141)

class MyClass142(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass142_swiginit(self, _SwigModule.new_MyClass142())
    __swig_destroy__ = _SwigModule.delete_MyClass142

# Register MyClass142 in _SwigModule:
_SwigModule.MyClass142_swigregister(MyClass142)

class MyClass143(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass143_swiginit(self, _SwigModule.new_MyClass143())
    __swig_destroy__ = _SwigModule.delete_MyClass143

# Register MyClass143 in _SwigModule:
_SwigModule.MyClass143_swigregister(MyClass143)

class MyClass144(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass144_swiginit(self, _SwigModule.new_MyClass144())
    __swig_destroy__ = _SwigModule.delete_MyClass144

# Register MyClass144 in _SwigModule:
_SwigModule.MyClass144_swigregister(MyClass144)

class MyClass145(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass145_swiginit(self, _SwigModule.new_MyClass145())
    __swig_destroy__ = _SwigModule.delete_MyClass145

# Register MyClass145 in _SwigModule:
_SwigModule.MyClass145_swigregister(MyClass145)

class MyClass146(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass146_swiginit(self, _SwigModule.new_MyClass146())
    __swig_destroy__ = _SwigModule.delete_MyClass146

# Register MyClass146 in _SwigModule:
_SwigModule.MyClass146_swigregister(MyClass146)

class MyClass147(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass147_swiginit(self, _SwigModule.new_MyClass147())
    __swig_destroy__ = _SwigModule.delete_MyClass147

# Register MyClass147 in _SwigModule:
_SwigModule.MyClass147_swigregister(MyClass147)

class MyClass148(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass148_swiginit(self, _SwigModule.new_MyClass148())
    __swig_destroy__ = _SwigModule.delete_MyClass148

# Register MyClass148 in _SwigModule:
_SwigModule.MyClass148_swigregister(MyClass148)

class MyClass149(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass149_swiginit(self, _SwigModule.new_MyClass149())
    __swig_destroy__ = _SwigModule.delete_MyClass149

# Register MyClass149 in _SwigModule:
_SwigModule.MyClass149_swigregister(MyClass149)

class MyClass150(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass150_swiginit(self, _SwigModule.new_MyClass150())
    __swig_destroy__ = _SwigModule.delete_MyClass150

# Register MyClass150 in _SwigModule:
_SwigModule.MyClass150_swigregister(MyClass150)

class MyClass151(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass151_swiginit(self, _SwigModule.new_MyClass151())
    __swig_destroy__ = _SwigModule.delete_MyClass151

# Register MyClass151 in _SwigModule:
_SwigModule.MyClass151_swigregister(MyClass151)

class MyClass152(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass152_swiginit(self, _SwigModule.new_MyClass152())
    __swig_destroy__ = _SwigModule.delete_MyClass152

# Register MyClass152 in _SwigModule:
_SwigModule.MyClass152_swigregister(MyClass152)

class MyClass153(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass153_swiginit(self, _SwigModule.new_MyClass153())
    __swig_destroy__ = _SwigModule.delete_MyClass153

# Register MyClass153 in _SwigModule:
_SwigModule.MyClass153_swigregister(MyClass153)

class MyClass154(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass154_swiginit(self, _SwigModule.new_MyClass154())
    __swig_destroy__ = _SwigModule.delete_MyClass154

# Register MyClass154 in _SwigModule:
_SwigModule.MyClass154_swigregister(MyClass154)

class MyClass155(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass155_swiginit(self, _SwigModule.new_MyClass155())
    __swig_destroy__ = _SwigModule.delete_MyClass155

# Register MyClass155 in _SwigModule:
_SwigModule.MyClass155_swigregister(MyClass155)

class MyClass156(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass156_swiginit(self, _SwigModule.new_MyClass156())
    __swig_destroy__ = _SwigModule.delete_MyClass156

# Register MyClass156 in _SwigModule:
_SwigModule.MyClass156_swigregister(MyClass156)

class MyClass157(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass157_swiginit(self, _SwigModule.new_MyClass157())
    __swig_destroy__ = _SwigModule.delete_MyClass157

# Register MyClass157 in _SwigModule:
_SwigModule.MyClass157_swigregister(MyClass157)

class MyClass158(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass158_swiginit(self, _SwigModule.new_MyClass158())
    __swig_destroy__ = _SwigModule.delete_MyClass158

# Register MyClass158 in _SwigModule:
_SwigModule.MyClass158_swigregister(MyClass158)

class MyClass159(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass159_swiginit(self, _SwigModule.new_MyClass159())
    __swig_destroy__ = _SwigModule.delete_MyClass159

# Register MyClass159 in _SwigModule:
_SwigModule.MyClass159_swigregister(MyClass159)

class MyClass160(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass160_swiginit(self, _SwigModule.new_MyClass160())
    __swig_destroy__ = _SwigModule.delete_MyClass160

# Register MyClass160 in _SwigModule:
_SwigModule.MyClass160_swigregister(MyClass160)

class MyClass161(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass161_swiginit(self, _SwigModule.new_MyClass161())
    __swig_destroy__ = _SwigModule.delete_MyClass161

# Register MyClass161 in _SwigModule:
_SwigModule.MyClass161_swigregister(MyClass161)

class MyClass162(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass162_swiginit(self, _SwigModule.new_MyClass162())
    __swig_destroy__ = _SwigModule.delete_MyClass162

# Register MyClass162 in _SwigModule:
_SwigModule.MyClass162_swigregister(MyClass162)

class MyClass163(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass163_swiginit(self, _SwigModule.new_MyClass163())
    __swig_destroy__ = _SwigModule.delete_MyClass163

# Register MyClass163 in _SwigModule:
_SwigModule.MyClass163_swigregister(MyClass163)

class MyClass164(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass164_swiginit(self, _SwigModule.new_MyClass164())
    __swig_destroy__ = _SwigModule.delete_MyClass164

# Register MyClass164 in _SwigModule:
_SwigModule.MyClass164_swigregister(MyClass164)

class MyClass165(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass165_swiginit(self, _SwigModule.new_MyClass165())
    __swig_destroy__ = _SwigModule.delete_MyClass165

# Register MyClass165 in _SwigModule:
_SwigModule.MyClass165_swigregister(MyClass165)

class MyClass166(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass166_swiginit(self, _SwigModule.new_MyClass166())
    __swig_destroy__ = _SwigModule.delete_MyClass166

# Register MyClass166 in _SwigModule:
_SwigModule.MyClass166_swigregister(MyClass166)

class MyClass167(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass167_swiginit(self, _SwigModule.new_MyClass167())
    __swig_destroy__ = _SwigModule.delete_MyClass167

# Register MyClass167 in _SwigModule:
_SwigModule.MyClass167_swigregister(MyClass167)

class MyClass168(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass168_swiginit(self, _SwigModule.new_MyClass168())
    __swig_destroy__ = _SwigModule.delete_MyClass168

# Register MyClass168 in _SwigModule:
_SwigModule.MyClass168_swigregister(MyClass168)

class MyClass169(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass169_swiginit(self, _SwigModule.new_MyClass169())
    __swig_destroy__ = _SwigModule.delete_MyClass169

# Register MyClass169 in _SwigModule:
_SwigModule.MyClass169_swigregister(MyClass169)

class MyClass170(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass170_swiginit(self, _SwigModule.new_MyClass170())
    __swig_destroy__ = _SwigModule.delete_MyClass170

# Register MyClass170 in _SwigModule:
_SwigModule.MyClass170_swigregister(MyClass170)

class MyClass171(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass171_swiginit(self, _SwigModule.new_MyClass171())
    __swig_destroy__ = _SwigModule.delete_MyClass171

# Register MyClass171 in _SwigModule:
_SwigModule.MyClass171_swigregister(MyClass171)

class MyClass172(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass172_swiginit(self, _SwigModule.new_MyClass172())
    __swig_destroy__ = _SwigModule.delete_MyClass172

# Register MyClass172 in _SwigModule:
_SwigModule.MyClass172_swigregister(MyClass172)

class MyClass173(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass173_swiginit(self, _SwigModule.new_MyClass173())
    __swig_destroy__ = _SwigModule.delete_MyClass173

# Register MyClass173 in _SwigModule:
_SwigModule.MyClass173_swigregister(MyClass173)

class MyClass174(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass174_swiginit(self, _SwigModule.new_MyClass174())
    __swig_destroy__ = _SwigModule.delete_MyClass174

# Register MyClass174 in _SwigModule:
_SwigModule.MyClass174_swigregister(MyClass174)

class MyClass175(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass175_swiginit(self, _SwigModule.new_MyClass175())
    __swig_destroy__ = _SwigModule.delete_MyClass175

# Register MyClass175 in _SwigModule:
_SwigModule.MyClass175_swigregister(MyClass175)

class MyClass176(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass176_swiginit(self, _SwigModule.new_MyClass176())
    __swig_destroy__ = _SwigModule.delete_MyClass176

# Register MyClass176 in _SwigModule:
_SwigModule.MyClass176_swigregister(MyClass176)

class MyClass177(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass177_swiginit(self, _SwigModule.new_MyClass177())
    __swig_destroy__ = _SwigModule.delete_MyClass177

# Register MyClass177 in _SwigModule:
_SwigModule.MyClass177_swigregister(MyClass177)

class MyClass178(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass178_swiginit(self, _SwigModule.new_MyClass178())
    __swig_destroy__ = _SwigModule.delete_MyClass178

# Register MyClass178 in _SwigModule:
_SwigModule.MyClass178_swigregister(MyClass178)

class MyClass179(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass179_swiginit(self, _SwigModule.new_MyClass179())
    __swig_destroy__ = _SwigModule.delete_MyClass179

# Register MyClass179 in _SwigModule:
_SwigModule.MyClass179_swigregister(MyClass179)

class MyClass180(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass180_swiginit(self, _SwigModule.new_MyClass180())
    __swig_destroy__ = _SwigModule.delete_MyClass180

# Register MyClass180 in _SwigModule:
_SwigModule.MyClass180_swigregister(MyClass180)

class MyClass181(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass181_swiginit(self, _SwigModule.new_MyClass181())
    __swig_destroy__ = _SwigModule.delete_MyClass181

# Register MyClass181 in _SwigModule:
_SwigModule.MyClass181_swigregister(MyClass181)

class MyClass182(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass182_swiginit(self, _SwigModule.new_MyClass182())
    __swig_destroy__ = _SwigModule.delete_MyClass182

# Register MyClass182 in _SwigModule:
_SwigModule.MyClass182_swigregister(MyClass182)

class MyClass183(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass183_swiginit(self, _SwigModule.new_MyClass183())
    __swig_destroy__ = _SwigModule.delete_MyClass183

# Register MyClass183 in _SwigModule:
_SwigModule.MyClass183_swigregister(MyClass183)

class MyClass184(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass184_swiginit(self, _SwigModule.new_MyClass184())
    __swig_destroy__ = _SwigModule.delete_MyClass184

# Register MyClass184 in _SwigModule:
_SwigModule.MyClass184_swigregister(MyClass184)

class MyClass185(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass185_swiginit(self, _SwigModule.new_MyClass185())
    __swig_destroy__ = _SwigModule.delete_MyClass185

# Register MyClass185 in _SwigModule:
_SwigModule.MyClass185_swigregister(MyClass185)

class MyClass186(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass186_swiginit(self, _SwigModule.new_MyClass186())
    __swig_destroy__ = _SwigModule.delete_MyClass186

# Register MyClass186 in _SwigModule:
_SwigModule.MyClass186_swigregister(MyClass186)

class MyClass187(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass187_swiginit(self, _SwigModule.new_MyClass187())
    __swig_destroy__ = _SwigModule.delete_MyClass187

# Register MyClass187 in _SwigModule:
_SwigModule.MyClass187_swigregister(MyClass187)

class MyClass188(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass188_swiginit(self, _SwigModule.new_MyClass188())
    __swig_destroy__ = _SwigModule.delete_MyClass188

# Register MyClass188 in _SwigModule:
_SwigModule.MyClass188_swigregister(MyClass188)

class MyClass189(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass189_swiginit(self, _SwigModule.new_MyClass189())
    __swig_destroy__ = _SwigModule.delete_MyClass189

# Register MyClass189 in _SwigModule:
_SwigModule.MyClass189_swigregister(MyClass189)

class MyClass190(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass190_swiginit(self, _SwigModule.new_MyClass190())
    __swig_destroy__ = _SwigModule.delete_MyClass190

# Register MyClass190 in _SwigModule:
_SwigModule.MyClass190_swigregister(MyClass190)

class MyClass191(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass191_swiginit(self, _SwigModule.new_MyClass191())
    __swig_destroy__ = _SwigModule.delete_MyClass191

# Register MyClass191 in _SwigModule:
_SwigModule.MyClass191_swigregister(MyClass191)

class MyClass192(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass192_swiginit(self, _SwigModule.new_MyClass192())
    __swig_destroy__ = _SwigModule.delete_MyClass192

# Register MyClass192 in _SwigModule:
_SwigModule.MyClass192_swigregister(MyClass192)

class MyClass193(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass193_swiginit(self, _SwigModule.new_MyClass193())
    __swig_destroy__ = _SwigModule.delete_MyClass193

# Register MyClass193 in _SwigModule:
_SwigModule.MyClass193_swigregister(MyClass193)

class MyClass194(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass194_swiginit(self, _SwigModule.new_MyClass194())
    __swig_destroy__ = _SwigModule.delete_MyClass194

# Register MyClass194 in _SwigModule:
_SwigModule.MyClass194_swigregister(MyClass194)

class MyClass195(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass195_swiginit(self, _SwigModule.new_MyClass195())
    __swig_destroy__ = _SwigModule.delete_MyClass195

# Register MyClass195 in _SwigModule:
_SwigModule.MyClass195_swigregister(MyClass195)

class MyClass196(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass196_swiginit(self, _SwigModule.new_MyClass196())
    __swig_destroy__ = _SwigModule.delete_MyClass196

# Register MyClass196 in _SwigModule:
_SwigModule.MyClass196_swigregister(MyClass196)

class MyClass197(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass197_swiginit(self, _SwigModule.new_MyClass197())
    __swig_destroy__ = _SwigModule.delete_MyClass197

# Register MyClass197 in _SwigModule:
_SwigModule.MyClass197_swigregister(MyClass197)

class MyClass198(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass198_swiginit(self, _SwigModule.new_MyClass198())
    __swig_destroy__ = _SwigModule.delete_MyClass198

# Register MyClass198 in _SwigModule:
_SwigModule.MyClass198_swigregister(MyClass198)

class MyClass199(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass199_swiginit(self, _SwigModule.new_MyClass199())
    __swig_destroy__ = _SwigModule.delete_MyClass199

# Register MyClass199 in _SwigModule:
_SwigModule.MyClass199_swigregister(MyClass199)

class MyClass200(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _SwigModule.MyClass200_swiginit(self, _SwigModule.new_MyClass200())
    __swig_destroy__ = _SwigModule.delete_MyClass200

# Register MyClass200 in _SwigModule:
_SwigModule.MyClass200_swigregister(MyClass200)



